# Generated by Django 3.2.5 on 2021-07-15 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('rut', models.CharField(error_messages={'unique': 'Un usuario con el mismo rut ya existe.'}, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'Un usuario con el mismo correo ya existe.'}, max_length=60, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('1', 'Estudiante'), ('2', 'Profesor'), ('3', 'Administrador')], max_length=30, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombreAsignatura', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estudiantes.usuario')),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
            bases=('estudiantes.usuario',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estudiantes.usuario')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.asignatura')),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
            bases=('estudiantes.usuario',),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1', models.FloatField(blank=True, null=True)),
                ('nota_2', models.FloatField(blank=True, null=True)),
                ('nota_3', models.FloatField(blank=True, null=True)),
                ('nota_4', models.FloatField(blank=True, null=True)),
                ('nota_5', models.FloatField(blank=True, null=True)),
                ('nota_6', models.FloatField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.asignatura')),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('nombreCurso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('alumnos', models.ManyToManyField(blank=True, to='estudiantes.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('asistencia', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=20, null=True)),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.asignatura')),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
            ],
        ),
    ]
